name: 'ls'
description: 'List contents of dir.'
inputs:
  dir:
    description: 'Directory to list.'
    required: true

runs:
  using: "composite"
  steps:
    - shell: bash
      run: ls -lar '${{ inputs.dir }}' 
